### ISSUE TITLE
Bug List for SuperAdmin

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#14]
1. Managing admins > Edit admin has a merchant form? Same for users too
2. Website is required ---> to be changed to optional, this field is broken hence cannot continue with the testing.
3. Boarding Status? What does not ready mean?
4. Merchant Type?

---**----------after accepting terms and condition 
5. Need a package here to determine the client's IP, this is a stupid requirement given that IPv4 for small businesses are dynamic. -- should be removed if not required.
6. Automate Date
7. Automate Time too
8. Need to display terms and condition with clickable links

----** ------general
9. Button remove the word in them and change the buttons to a floating + sign)
10. Add deal --- outstanding
11. Click on image bring user to profile page. Click on word or down-arrow will show dropdown arrow.
12. Profile Update o/s

**Comment by vinaybagale** [comment]
1. Managing admins > Edit admin has a merchant form? Same for users too. 
**comment** : Form will be replaced with Admin & User functionality completed.

2. Website is required ---> to be changed to optional, this field is broken hence cannot continue with the testing.
**comment** : Done, Changed it to optional

3. Boarding Status? What does not ready mean?
**comment** : Discussed & Closed (i.e. Not Ready & Board immediately, which allow to onboard merchant immediately or later on splash)

4. Merchant Type?
**comment** : Discussed & Closed (i.e. MerchantType will be Supermarket, Fuel, Restaurant or eCommerce etc.)

---**----------after accepting terms and condition
5. Need a package here to determine the client's IP, this is a stupid requirement given that IPv4 for small businesses are dynamic. -- should be removed if not required.
**comment** : Discussed & On Hold (i.e. User need to enter static IP of merchant)

6. Automate Date
**comment** : Done, As discussed, current date will be added

7. Automate Time too
**comment** : Done, Current time will be added

8. Need to display terms and condition with clickable links
**comment** : Done, Added option to select and view Terms and Conditions.

----** ------general
9. Button remove the word in them and change the buttons to a floating + sign)
**comment** : Done, As discussed, Implemented Floating Action Buttons of material UI

10. Add deal --- outstanding
**comment** : Done, Deal section completed from web app front.

11. Click on image bring user to profile page. Click on word or down-arrow will show dropdown arrow.
**comment** : Done, Implemented as directed.

12. Profile Update o/s
**comment** : Outstanding, This will be next task on list to complete.

**Comment by vinaybagale** [comment]
**---> Fixed**

**Comment by bibhav58** [comment]
re-test successful

closing the defect
