### ISSUE TITLE
Additional Issues on Merchant App

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#19]
1. Cannot add a new merchant..got an error message, "Failed to process your request"…even afer entering the actual routing number for BOA
2.Cannot activate expired status.
While trying to edit active detals, got error message, "Your submission could not be completed. Please Try Again!"
3. Cannot add admins being a super admin
As a superadmin, I deleted a user, the status shows ‘Deactive’..now I cannot activate the same user.
4. Cannot add after entering mode name
5. Cannot activate deactive merchant
6.  cannot activate expired status.
While trying to edit active detals, got error message, "Your submission could not be completed. Please Try Again!"
7.

**Comment by vinaybagale** [comment]
**---> Fixed**

**Comment by bibhav58** [comment]
re-test successful

closing the defect
