### ISSUE TITLE
mcc : Invalid mcc

### ISSUE THREAD

**Issue by bibhav58** [swiperewards/Web-App#20]
![invalid mcc 2](https://user-images.githubusercontent.com/43385305/45707373-ad0cb580-bb4c-11e8-9346-4925ce77c1ac.png)
![invalid mcc](https://user-images.githubusercontent.com/43385305/45707374-ad0cb580-bb4c-11e8-9d2b-5a1ca7126918.png)

**Comment by bibhav58** [comment]
MCC code: 0742 giving error message, "mcc: invalid mcc".

**Comment by bibhav58** [comment]
I was able to add a merchant with different mcc code but not with mcc 0742

**Comment by vinaybagale** [comment]
MCC code: 0742 giving error message, "mcc: invalid mcc".

---> MCC Code verified by splash SDK, We have raised ticket to splash regarding this error.

**Comment by vinaybagale** [comment]
Only provided MCC code will be displayed

**Comment by ptxd** [comment]
Fixed
