### ISSUE TITLE
Merchant Web App Not Working After Merchant Onboarding

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#21]
Merchant Web 

Once a merchant has been onboard via the form in payment processing, the merchant is seeing other merchant accounts on the table. The merchant is unable to view their own account or create a new deal on the platform.

**Comment by vinaybagale** [comment]
-- "Ali Bhai" is not visible on "Manage Deals" under merchant web.

--->Fixed

**Comment by bibhav58** [comment]
re-test successful

closing the defect
