### ISSUE TITLE
Get admin list with filter option

### ISSUE THREAD

**Issue by bibhav58** [swiperewards/Web-App#23]
![after entering status](https://user-images.githubusercontent.com/43385305/45722365-fcb5a600-bb79-11e8-8bbf-7f934fd5f2df.png)
![without entering status](https://user-images.githubusercontent.com/43385305/45722367-fcb5a600-bb79-11e8-8fa0-b6ca458fe987.png)

**Comment by bibhav58** [comment]
Scenario 1: Filter works if I don't enter the status

Scenario 2: Filter doesn't work if i enter status

**Comment by vinaybagale** [comment]
Scenario 1: Filter works if I don't enter the status  

Scenario 2: Filter doesn't work if i enter status

**---> (Fixed)**

**Comment by bibhav58** [comment]
Re-tested...works perfect now. 

Closing the defect.
