### ISSUE TITLE
Update/Delete admin feature implemented

### ISSUE THREAD

**Issue by bibhav58** [swiperewards/Web-App#24]
![p s maind 1](https://user-images.githubusercontent.com/43385305/45723427-448afc00-bb7f-11e8-9699-24eb0ed15998.png)
![p s maind 2](https://user-images.githubusercontent.com/43385305/45723428-448afc00-bb7f-11e8-9946-13fa19c8459d.png)

**Comment by bibhav58** [comment]
Scenario 1: under 'Update Admin' tab--when I change the status to 'Activate' and click 'Update' the status gets changed to 'Deactive' 
Scenario 2: under 'Update Admin' tab--when I change the status to 'Deactivate' and click 'Update' the status gets changed to 'Active'

**Comment by vinaybagale** [comment]
Scenario 1: under 'Update Admin' tab--when I change the status to 'Activate' and click 'Update' the status gets changed to 'Deactive' .  **----> (Fixed)**
Scenario 2: under 'Update Admin' tab--when I change the status to 'Deactivate' and click 'Update' the status gets changed to 'Active' **----> (Fixed)**

**Comment by vinaybagale** [comment]
I can see that the status is no longer upside down but once I change the status and click update the page doesn't load. It doesn't give me the message saying, "successfully updated".

**----> Fixed**

**Comment by bibhav58** [comment]
re-test successful

closing the defect
