### ISSUE TITLE
Bug related to deals

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#25]
1. When dealing with dates, use the calendar feature provided by material UI to make it easier to select the dates.
2. City not listed on the deals --- it lists state
3. Deals not showing up on android app

**Comment by vinaybagale** [comment]
1. When dealing with dates, use the calendar feature provided by material UI to make it easier to select the dates.   **----> (Waiting for Design mock)**
2. City not listed on the deals --- it lists state .  **----> (Fixed)**
3. Deals not showing up on android app **----> (Fixed)**

**Comment by vinaybagale** [comment]
1. When dealing with dates, use the calendar feature provided by material UI to make it easier to select the dates. ----> (Fixed)
2. City not listed on the deals --- it lists state . ----> (Fixed)
3. Deals not showing up on android app ----> (Fixed)

**Comment by bibhav58** [comment]
re-tested...works perfect.

closing the defect.
