### ISSUE TITLE
Superadmin-->Manage Users

### ISSUE THREAD

**Issue by bibhav58** [swiperewards/Web-App#28]
![with status](https://user-images.githubusercontent.com/43385305/45858735-e865da80-bd2c-11e8-83cc-db55cccf5366.png)
![without status](https://user-images.githubusercontent.com/43385305/45858736-e8fe7100-bd2c-11e8-90eb-0262e67f703b.png)

**Comment by bibhav58** [comment]
Works when status is not entered
Doesn't work if status is entered.

**Comment by vinaybagale** [comment]
Works when status is not entered
Doesn't work if status is entered.

**----->(Fixed)**

**Comment by bibhav58** [comment]
re-tested...works perfect now.

closing the defect.
