### ISSUE TITLE
Activation Toggle 

### ISSUE THREAD

**Issue by bibhav58** [swiperewards/Web-App#31]
![activation switch](https://user-images.githubusercontent.com/43385305/45983153-8d343080-c029-11e8-85bc-22e9fa297a1d.png)

**Comment by bibhav58** [comment]
Please make the activation toggle opposite meaning...green for 'Active' status and 'Grey' for 'Deactive' status.

**Comment by ptxd** [comment]
This issue has been tested and closed --
