### ISSUE TITLE
Manage Deals - Merchant Facing

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#37]
Able to see other people's deals.

**Comment by ptxd** [comment]
When a merchant clicks on the + button usually you are to guide the merchant in creating a deal.

**Comment by vinaybagale** [comment]
Able to see other people's deals.
**---> (Fixed)**

When a merchant clicks on the + button usually you are to guide the merchant in creating a deal.
**(This was discussed over skype call as hold on same functionality)**
