### ISSUE TITLE
Able to change amount in deals

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#42]
While a superadmin is able to change the amount of a deal wether to increase it or decrease it, the merchant or a superadmin should not be given the rights to do this.

**Comment by vinaybagale** [comment]
While a superadmin is able to change the amount of a deal wether to increase it or decrease it, the merchant or a superadmin should not be given the rights to do this.

---> (Fixed)

**Comment by ptxd** [comment]
Merchant unable to change the amount need to validate admin cant update deal and superadmin is the only authorization level allowed to authorize the deal
