### ISSUE TITLE
Merchant Facing -- Remove Field issue #36

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#55]
![image](https://user-images.githubusercontent.com/27824585/47693014-17396100-dbb5-11e8-810a-5edccad7c937.png)

Remove the IP Field -- automate this

**Comment by ptxd** [comment]
Either remove the field or pre-populate

**Comment by vinaybagale** [comment]
**--> Fixed**, Field will be pre-populated

**Comment by ptxd** [comment]
Prepopulated field not displaying

**Comment by vinaybagale** [comment]
Fixed, Available in production now.
