### ISSUE TITLE
Merchant Registration Fields --- Recommended Changes

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Web-App#58]
![image](https://user-images.githubusercontent.com/27824585/49057245-93729480-f1b3-11e8-955f-345965002d0a.png)

1. Years in business --- should be changed to start date of business (years in business requires a whole number, while start date requires the start date of the business)

2. Website (change to optional)

**Comment by vinaybagale** [comment]
Fixed, Changes are deployed on production instance.
